### ISSUE TITLE
add9 chords are not found

### ISSUE THREAD

**Issue by greird** [greird/chordictionaryjs#8]
x32030 is not recognized as a Cadd9 chord. 
When generating a Cadd9 chord, the tab returned is x32020, which is wrong (it would be a Cadd9min).

**Comment by torqueville** [comment]
That voicing works when using integer 2 instead of 14 in the formula:

```
      {formula:"1-3-5-9",           integer:"0-4-7-14",           name:"Major, add nine",                   suffix:"add9"      },
      {formula:"1-3-5-9",           integer:"0-2-4-7",            name:"Major, add nine",                   suffix:"add9"      },
```

Same thing with Cm(add9) x3103x

`      {formula:"1-b3-5-9",          integer:"0-3-7-14",           name:"Minor, add nine",                   suffix:"m(add9)"   },
      {formula:"1-b3-5-9",          integer:"0-2-3-7",            name:"Minor, add nine",                   suffix:"m(add9)"   },`

**Comment by greird** [comment]
Same as #10
