### ISSUE TITLE
6/9 chords are not found

### ISSUE THREAD

**Issue by greird** [greird/chordictionaryjs#9]
xx1091010 or x1212121312 are not recognized as C6/9 chords.
However, it recognizes the right notes xADGCE.

When generating a C6/9 chord, it generate the following tab : x32223 with the following notes xCEAC#G. This is wrong. C# should be replaced with a D.

**Comment by torqueville** [comment]
Same thing as with the Cmaj9 goes for 6/9 chords (x32233). That is, defining the nine by integer 2 instead of integer 14. 

This formula works: 

```
{formula:"1-3-5-6-9",         integer:"0-2-4-7-9",          name:"Major six, added nine",              suffix:"6/9"  },
```
And C6/9(no5) voicing x3223x works with this formula:

```
{formula:"1-3-6-9",           integer:"0-2-4-9",            name:"Major six, added nine",              suffix:"6/9(no5)" },
```

**Comment by greird** [comment]
Same as #10
